---
version: '2'

services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2017-CU20-ubuntu-16.04"
    container_name: mssql-meta
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MetaChallenge2020
    ports:
      - "1433:1433"
